//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarCostCalculator_App.CCL.Components.WebAssembly.Localization
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonTranslations
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonTranslations()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Swietelsky.Basement.Components.WebAssembly.Localization.CommonTranslations", typeof(CommonTranslations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add
        {
            get
            {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Authorizing.
        /// </summary>
        public static string Authorizing
        {
            get
            {
                return ResourceManager.GetString("Authorizing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string Branch
        {
            get
            {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel
        {
            get
            {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Changes you made may not be saved..
        /// </summary>
        public static string ChangesWarning
        {
            get
            {
                return ResourceManager.GetString("ChangesWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        public static string Collapse
        {
            get
            {
                return ResourceManager.GetString("Collapse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The item you were trying to update has been modified by someone else. Please reopen to see the latest changes..
        /// </summary>
        public static string Concurrency_Conflict
        {
            get
            {
                return ResourceManager.GetString("Concurrency Conflict", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Swietelsky Data Hub is the central hub for company-wide core data..
        /// </summary>
        public static string DataHub
        {
            get
            {
                return ResourceManager.GetString("DataHub", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete
        {
            get
            {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete all search terms.
        /// </summary>
        public static string DeleteAllSearchTerms
        {
            get
            {
                return ResourceManager.GetString("DeleteAllSearchTerms", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Disable all filters..
        /// </summary>
        public static string DisableFilters
        {
            get
            {
                return ResourceManager.GetString("DisableFilters", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This data record already exists.
        /// </summary>
        public static string DuplicateDataRecord
        {
            get
            {
                return ResourceManager.GetString("DuplicateDataRecord", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit
        {
            get
            {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to E-Mail Address.
        /// </summary>
        public static string EMailAddress
        {
            get
            {
                return ResourceManager.GetString("EMailAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Employee Number.
        /// </summary>
        public static string EmployeeNumber
        {
            get
            {
                return ResourceManager.GetString("EmployeeNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Entry Date.
        /// </summary>
        public static string EntryDate
        {
            get
            {
                return ResourceManager.GetString("EntryDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error communicating with the server! Try again. If it doesn&apos;t work, please contact the administrator!.
        /// </summary>
        public static string ErrorCommunication
        {
            get
            {
                return ResourceManager.GetString("ErrorCommunication", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No permission! Try again. If it doesn&apos;t work, please contact the administrator!.
        /// </summary>
        public static string ErrorForbidden
        {
            get
            {
                return ResourceManager.GetString("ErrorForbidden", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An error occurred! Try again. If it doesn&apos;t work, please contact the administrator!.
        /// </summary>
        public static string ErrorGeneral
        {
            get
            {
                return ResourceManager.GetString("ErrorGeneral", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error logging in! Please try again..
        /// </summary>
        public static string ErrorLogin
        {
            get
            {
                return ResourceManager.GetString("ErrorLogin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not authorized to access.
        /// </summary>
        public static string ErrorUnauthorized
        {
            get
            {
                return ResourceManager.GetString("ErrorUnauthorized", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expand.
        /// </summary>
        public static string Expand
        {
            get
            {
                return ResourceManager.GetString("Expand", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName
        {
            get
            {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to for.
        /// </summary>
        public static string For
        {
            get
            {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello
        {
            get
            {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to is invalid.
        /// </summary>
        public static string IsInvalid
        {
            get
            {
                return ResourceManager.GetString("IsInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to is not loaded!.
        /// </summary>
        public static string IsNotLoaded
        {
            get
            {
                return ResourceManager.GetString("IsNotLoaded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to is required.
        /// </summary>
        public static string IsRequired
        {
            get
            {
                return ResourceManager.GetString("IsRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName
        {
            get
            {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Level
        {
            get
            {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading
        {
            get
            {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name
        {
            get
            {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No
        {
            get
            {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not authorized to view this page..
        /// </summary>
        public static string NotAuthorizedToViewThisPage
        {
            get
            {
                return ResourceManager.GetString("NotAuthorizedToViewThisPage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to not available.
        /// </summary>
        public static string NotAvailable
        {
            get
            {
                return ResourceManager.GetString("NotAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes
        {
            get
            {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        public static string NotFound
        {
            get
            {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Office.
        /// </summary>
        public static string Office
        {
            get
            {
                return ResourceManager.GetString("Office", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok
        {
            get
            {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Organizational Unit.
        /// </summary>
        public static string OrganizationalUnit
        {
            get
            {
                return ResourceManager.GetString("OrganizationalUnit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sorry, there&apos;s nothing at this address..
        /// </summary>
        public static string PageNotFound
        {
            get
            {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role
        {
            get
            {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save
        {
            get
            {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save Anyways.
        /// </summary>
        public static string SaveAnyways
        {
            get
            {
                return ResourceManager.GetString("SaveAnyways", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search
        {
            get
            {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter a term and press Enter.
        /// </summary>
        public static string SearchBarPlaceholderText
        {
            get
            {
                return ResourceManager.GetString("SearchBarPlaceholderText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter a term.
        /// </summary>
        public static string SearchBarPlaceholderTextSingleMode
        {
            get
            {
                return ResourceManager.GetString("SearchBarPlaceholderTextSingleMode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Info: Enter at least 3 characters to start the search.
        /// </summary>
        public static string SearchHelperText
        {
            get
            {
                return ResourceManager.GetString("SearchHelperText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show all Columns.
        /// </summary>
        public static string ShowAllColumns
        {
            get
            {
                return ResourceManager.GetString("ShowAllColumns", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        public static string UniqueNumber
        {
            get
            {
                return ResourceManager.GetString("UniqueNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning
        {
            get
            {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        public static string Welcome
        {
            get
            {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Swietelsky Data Hub!.
        /// </summary>
        public static string WelcomeMessage
        {
            get
            {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes
        {
            get
            {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}

